### ISSUE TITLE
Latest versions of selenium webdriver and firefox require installation of geckodriver

### ISSUE THREAD

**Issue by mikeries** [learn-co-students/return-string-data-lab-v-000#201]
I couldn't get the selenium webdriver tests to run because of this issue:[https://github.com/seleniumhq/selenium/issues/835](https://github.com/seleniumhq/selenium/issues/835)

To resolve the problem, I ran `bundle update` which told me to install the geckodriver from here: [https://github.com/mozilla/geckodriver/releases](https://github.com/mozilla/geckodriver/releases)

I downloaded it, extracted it, and moved it to my /bin directory (Xubuntu) and the tests run now.  Next step, turn them green!

**Comment by cernanb** [comment]
Thanks for this Michael! Installing poltergeist is another fix...and I merged that in just now. Hopefully future students don't come across this issue.
